sonar.projectKey=3nibbles
sonar.projectName=3nibbles
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.exclusions=build/**,cmake-build-debug/**,.idea/**
