sonar.projectKey=3nibbles
sonar.projectName=3nibbles
sonar.sourceEncoding=UTF-8

sonar.sources=src,include
sonar.tests=tests
sonar.test.inclusions=tests/**/*.cpp

sonar.cfamily.compile-commands=build/compile_commands.json
sonar.coverageReportPaths=build/coverage/sonarqube-coverage.xml
sonar.exclusions=build/**,cmake-build-debug/**,.idea/**
